//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Control_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class community
    {
        public int id { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<System.DateTime> publshDate { get; set; }
        public Nullable<int> likes { get; set; }
        public Nullable<int> reportCounter { get; set; }
        public string comment { get; set; }
    }
}
